<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSGPlFSc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSGPlFSc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSGPlFSc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSGPlFSc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSGPlFSc\App_KernelDevDebugContainer([
    'container.build_hash' => 'SGPlFSc',
    'container.build_id' => 'b59c731f',
    'container.build_time' => 1625050917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSGPlFSc');
